let nombre = "Luis";
console.log(nombre);
console.log(typeof nombre);
let apellido = "Curzi";
console.log(apellido);
console.log(typeof apellido);
let edad = "18";
console.log(edad);
console.log(typeof edad);
let numerodetelefono = "1124345464";
console.log(numerodetelefono);
console.log(typeof numerodetelefono);
let socio = "si";
console.log(socio);
console.log(typeof socio);
let fechadelpartido = "19/04/24";
console.log(fechadelpartido);
console.log(typeof fechadelpartido);
let horadelpartido = "16:30";
console.log(horadelpartido);
console.log(typeof horadelpartido);
let numerodesilla = "18";
console.log(numerodesilla);
console.log(typeof numerodesilla);
let presiodelboleto = "5.000";
console.log(presiodelboleto);
console.log(typeof presiodelboleto);